---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

# Motivation
***

* In a pre-election poll, only 37% of Americans said the country is on the right track.

* In the 2020 presidential election, COVID-19 has been one of the key issue directing people's choice.

* Among those who considered coronavirus pandemic as the most mattered issue, 81% voted Biden while only 15% voted Trump.

* However, there is also report stating that in places where the virus is most rampant now, Trump enjoyed enormous support.

* Many voters who voted Trump 2016 said they are turning to Biden this year 

\

# Related work
***

The following are resources that inspire our work:


* [National Exit Polls: How Different Groups Voted](https://www.nytimes.com/interactive/2020/11/03/us/elections/exit-polls-president.html)

* [Analysis: Counties with the worst virus surges overwhelmingly voted for Trump](https://www.kxnet.com/news/national-news/counties-with-the-worst-virus-surges-overwhelmingly-voted-for-trump/)

* [Counties with worst COVID-19 surges overwhelmingly voted Trump in 2020 presidential election](https://abc11.com/politics/counties-with-worst-covid-19-surges-overwhelmingly-voted-trump/7683127/)

* [Voter Survey: U.S. Is On Wrong Track, COVID-19 Not Under Control](https://www.npr.org/2020/11/03/930956115/voter-survey-u-s-is-on-wrong-track-covid-19-not-under-control)

\

# Initial questions
***

Initially, we would like to focus on all states. But as our project progressed, we found it would be more meaningful to only focus on swing states.

Therefore, in this analysis, we focused primarily on top battleground states, including Florida, Pennsylvania, Wisconsin, North Carolina, Michigan, Ohio, Minnesota, Iowa, Arizona, Nevada, Texas, Georgia, Virginia, New Hampshire, Maine,Colorado and New Mexico.

Targeting these states, we aimed to answer the following questions:

* What is the time trend of COVID-19 statistics and presidential poll in 2020?

* How COVID-19 is correlated with presidential supporting rate in 2020?

* How is democrats / republican supporting rate in 2020 compared to 2016?

* Is there any distribution worth noting among mail-in vote?

\

# Data

## Data source
Our analysis based on the following data source:

* [2016 & 2020 presidential poll](https://www.realclearpolitics.com/)

* [Mail-in vote data](https://electproject.github.io/)

* [COVID-19 data](http://covidtracking.com/data/)

\

## Data scraping and cleaning
***

### Presidential poll 

All presidential poll by states were read and then selected by CSS selector. Relevant tables were scraped as tibbles with map and function statement. The supporting rate (`biden` and `trump`), spread (`spread`), poll period (`start_date` and `end_date`) and poll agent (`poll`) were selected. All date was transformed to date format in R for later analysis. 
`spread` was further transformed into `biden_lead` to represent the difference between the supporting rate of Biden and Trump.

**Variables**

* `state`: The battbleground state name

* `poll`: The poll agent

* `start_date`: The start date of the poll survey period

* `end_date`: The end date of the poll survey period

* `biden`: The supporting rate(%) of Mr.Biden

* `trump`: The supporting rate(%) of Mr.Trump

* `biden_lead`: The difference of supporting rate (%) between Biden and Trump. Positive number indicates Biden over Trump while negative number indicates Trump over Biden

### Mail-in vote data

Mail-in vote data was scraped using Xpath statement. Mail ballots returned and accepted by party registration are used in our analysis. Some battleground states did not report the mail-in statistics. Therefore, only Florida, Pennsylvania, North Carolina, Iowa, Arizona and Nevada were included in related analysis.

**Variables**

* `state`: The battleground state name

* `party`: Category variable of supporting party including: Democrats, Republicans, Minor, No Party Affiliation and Total

* `requested_ballots`: The number of ballots that have been requested

* `returned_ballots`: The number of ballots that have been returned

* `return_rate`: The rate of returned ballots over requested ballots

* `freq_distribution`: The corresponding frequency (%) of each party

## COVID-19 data

# Exploratory analysis
***

## Supporting rate comparison

In 2016, 7 of the 17 battleground states have the Democratic supporting rates higher than the Republican supporting rates. In 2020, 12 of the 17 battleground states have the Democratic supporting rates higher than the Republican supporting rates. We observed that in each of the battleground states, the difference between Democratic supporting rate and Republican supporting rate has increased, except Florida and Ohio. 

# Statistical analysis
***

## Supporting rate comparison

We observed that in each of the battleground states, the difference between Democratic supporting rate and Republican supporting rate has increased, except Florida and Ohio. This result represents that the extent of how much the Democrat led has increased in 15 of the 17 key states.

# Discussion
***

## Supporting rate comparison

In 2016, only 7 of the 17 battleground states were blue states, which supported the Democratic party. However, in 2020, 12 of the 17 battleground states were blue states. Five new blue states included Arizona, Georgia, Michigan, Pennsylvania, and Wisconsin. We observed an increase in the extent of how much Democrats led in 15 states. Only Florida and Ohio had their Republican supporting rates increased in 2020. Overall, we could figure out that since the Democratic party led in most of the battleground states in 2020, it is reasonable to predict and understand why the Democrats would win in the 2020 election.